// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzd_oguFT5ZrxypPrGTTIuM2--z-8EVYA',
    appId: '1:991404450534:android:11e10dc6acd777dd2ed127',
    messagingSenderId: '991404450534',
    projectId: 'tp-flutter-firebase-8854f',
    storageBucket: 'tp-flutter-firebase-8854f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbAzrwn5barWHbKh_Fu3uDSUYMHw6oqo8',
    appId: '1:991404450534:ios:ef40ce16f83d5bf42ed127',
    messagingSenderId: '991404450534',
    projectId: 'tp-flutter-firebase-8854f',
    storageBucket: 'tp-flutter-firebase-8854f.appspot.com',
    androidClientId: '991404450534-ggphqifbv5sbs2dlue9ofp8jsnp49ttl.apps.googleusercontent.com',
    iosClientId: '991404450534-uuja9ue7q5tr7r7bd1g8dsl2riga7baj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpFlutterFirebase',
  );
}
